### ISSUE TITLE
No license attached

### ISSUE THREAD

**Issue by michael-schnell** [shibme/jira-api#1]
Your source looks quite interesting, but unfortunately there is no license attached. 

How about using a standard license model like [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) oder [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.de.html)?

A more general question: What is the difference to the official [JIRA REST API Client](https://ecosystem.atlassian.net/wiki/spaces/JRJC/overview)?

**Comment by shibme** [comment]
You must have missed to notice that there is a [license](https://github.com/shibme/jira-api/blob/master/LICENSE) attached already.
This is the Java implementation of the same. This was forked from a discontinued project for further development.

**Comment by shibme** [comment]
Also this was rather simpler. Though actually started even before they had a java client, I forked and published it recently.
